/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertError: typeof import('./resources/js/components/AlertError.vue')['default']
    AppLogo: typeof import('./resources/js/components/AppLogo.vue')['default']
    AppLogoIcon: typeof import('./resources/js/components/AppLogoIcon.vue')['default']
    CustomersAddModal: typeof import('./resources/js/components/customers/CustomersAddModal.vue')['default']
    CustomersDeleteModal: typeof import('./resources/js/components/customers/CustomersDeleteModal.vue')['default']
    DeleteAccount: typeof import('./resources/js/components/DeleteAccount.vue')['default']
    HomeChart: typeof import('./resources/js/components/home/HomeChart.vue')['default']
    HomeDateRangePicker: typeof import('./resources/js/components/home/HomeDateRangePicker.vue')['default']
    HomePeriodSelect: typeof import('./resources/js/components/home/HomePeriodSelect.vue')['default']
    HomeSales: typeof import('./resources/js/components/home/HomeSales.vue')['default']
    HomeStats: typeof import('./resources/js/components/home/HomeStats.vue')['default']
    InboxList: typeof import('./resources/js/components/inbox/InboxList.vue')['default']
    InboxMail: typeof import('./resources/js/components/inbox/InboxMail.vue')['default']
    NotificationsSlideover: typeof import('./resources/js/components/NotificationsSlideover.vue')['default']
    SettingsMembersList: typeof import('./resources/js/components/settings/SettingsMembersList.vue')['default']
    TeamsMenu: typeof import('./resources/js/components/TeamsMenu.vue')['default']
    TextLink: typeof import('./resources/js/components/TextLink.vue')['default']
    TwoFactor: typeof import('./resources/js/components/TwoFactor.vue')['default']
    TwoFactorRecoveryCodes: typeof import('./resources/js/components/TwoFactorRecoveryCodes.vue')['default']
    TwoFactorSetupModal: typeof import('./resources/js/components/TwoFactorSetupModal.vue')['default']
    UserMenu: typeof import('./resources/js/components/UserMenu.vue')['default']
  }
}
